/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCommentReads"];
        put?: never;
        post: operations["createCommentCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["retrieveCommentRead"];
        put: operations["updateCommentUpdate"];
        post?: never;
        delete: operations["destroyCommentRead"];
        options?: never;
        head?: never;
        patch: operations["partialUpdateCommentUpdate"];
        trace?: never;
    };
    "/api/events/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEventReads"];
        put?: never;
        post: operations["createEventCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/options/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["optionsEventRead"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["retrieveEventRead"];
        put: operations["updateEventUpdate"];
        post?: never;
        delete: operations["destroyEventRead"];
        options?: never;
        head?: never;
        patch: operations["partialUpdateEventUpdate"];
        trace?: never;
    };
    "/api/events/{id}/highlights/{highlight_pk}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["highlightDetailEventRead"];
        put?: never;
        post?: never;
        delete: operations["highlightDetailEventRead"];
        options?: never;
        head?: never;
        patch: operations["highlightDetailEventRead"];
        trace?: never;
    };
    "/api/events/{id}/highlights/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["highlightsEventRead"];
        put?: never;
        post: operations["highlightsEventRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/participants/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["participantsEventRead"];
        put?: never;
        post: operations["participantsEventRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/photos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["photosEventRead"];
        put?: never;
        post: operations["photosEventRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/photos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPhotos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/photos/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["retrievePhoto"];
        put: operations["updatePhoto"];
        post?: never;
        delete: operations["destroyPhoto"];
        options?: never;
        head?: never;
        patch: operations["partialUpdatePhoto"];
        trace?: never;
    };
    "/api/monitoring/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listhealthchecks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUsers"];
        put?: never;
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["retrieveUser"];
        put: operations["updateUser"];
        post?: never;
        delete: operations["destroyUser"];
        options?: never;
        head?: never;
        patch: operations["partialUpdateUser"];
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createForgotAccess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPasswordResetConfirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/onboarding/complete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createOnboardingFirstAccess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelEventRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/reactivate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reactivateEventRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/restore/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restoreEventRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations/github/webhook/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createGithubWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/photos/upload-urls/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPhotoUploadUrls"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/photos/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPhotoConfirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/uploads/signed-url/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createUserUploadSignedUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/thumbnail/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["thumbnailEventRead"];
        post?: never;
        delete: operations["thumbnailEventRead"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/participants/{user_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeParticipantEventRead"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/photos/{photo_pk}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["unlinkPhotoActionEventRead"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CommentRead: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            readonly author_id?: string;
            readonly author_name?: string;
            readonly body?: string;
            /** Format: uuid */
            readonly parent_id?: string;
            readonly target_type?: string;
            /** Format: uuid */
            readonly target_id?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            readonly is_deleted?: string;
        };
        EventRead: {
            /** Format: uuid */
            readonly id?: string;
            readonly title?: string;
            readonly description?: string;
            /** Format: date-time */
            readonly start_at?: string;
            /** Format: date-time */
            readonly end_at?: string;
            /** @enum {string} */
            readonly type?: "UNIVERSITY_PARTY" | "BIRTHDAY" | "CLUB" | "CASUAL_HANGOUT" | "BARBECUE" | "AFTER_PARTY" | "GRADUATION" | "SHOW" | "FESTIVAL" | "DINNER" | "TRIP" | "CABULOUS" | "CINEMA";
            readonly type_color?: string;
            /** @enum {string} */
            readonly status?: "SCHEDULED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
            /** Format: date-time */
            readonly cancelled_at?: string | null;
            readonly audiences?: string;
            readonly participants_count?: string;
            readonly location?: {
                /** Format: uuid */
                readonly id?: string;
                readonly name?: string;
                readonly address?: string;
                /** Format: decimal */
                readonly latitude?: string;
                /** Format: decimal */
                readonly longitude?: string;
            };
            readonly thumbnail_url?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        Photo: {
            /** Format: uuid */
            readonly id?: string;
            readonly object_key?: string;
            readonly uploader?: string;
            /** Format: date */
            taken_on: string;
            caption?: string;
            readonly content_type?: string;
            readonly size_bytes?: number;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        User: {
            /** Format: uuid */
            readonly id?: string;
            username: string;
            /** Format: email */
            email: string;
            first_name?: string;
            last_name?: string;
            discord_username?: string;
            phone_number?: string;
            /** Format: binary */
            readonly avatar?: string | null;
            avatar_key?: string;
            /** Format: binary */
            readonly banner?: string | null;
            banner_key?: string;
            bio?: string;
            /** Format: date-time */
            onboarding_completed_at?: string | null;
            /** Format: date-time */
            password_defined_at?: string | null;
            /** Format: date-time */
            invited_at?: string | null;
            /** Format: date-time */
            invitation_accepted_at?: string | null;
            /** @description Indica que o usuário será tratado como ativo. Ao invés de excluir contas de usuário, desmarque isso. */
            is_active?: boolean;
            /** @description Indica que usuário consegue acessar este site de administração. */
            is_staff?: boolean;
            /** @description Indica que este usuário tem todas as permissões sem atribuí-las explicitamente. */
            is_superuser?: boolean;
            /** @description Os grupos que este usuário pertence. Um usuário terá todas as permissões concedidas a cada um dos seus grupos. */
            groups?: number[];
            /** @description Permissões específicas para este usuário. */
            user_permissions?: number[];
            /** Format: date-time */
            readonly last_login?: string | null;
            /** Format: date-time */
            readonly date_joined?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            /** Format: date-time */
            readonly deleted_at?: string | null;
        };
        CommentCreate: {
            target_type: string;
            /** Format: uuid */
            target_id: string;
            body: string;
            /** Format: uuid */
            parent_id?: string | null;
        };
        EventCreate: {
            title: string;
            /** @default  */
            description: string;
            /** Format: date-time */
            start_at: string;
            /** Format: date-time */
            end_at: string;
            /** @enum {string} */
            type: "UNIVERSITY_PARTY" | "BIRTHDAY" | "CLUB" | "CASUAL_HANGOUT" | "BARBECUE" | "AFTER_PARTY" | "GRADUATION" | "SHOW" | "FESTIVAL" | "DINNER" | "TRIP" | "CABULOUS" | "CINEMA";
            audiences: ("ILUMINADOS" | "VOYEURS" | "ELETRONICOS" | "OTHERS")[];
            location?: {
                /** @default  */
                name: string;
                address: string;
                /** Format: decimal */
                latitude: string;
                /** Format: decimal */
                longitude: string;
            };
        };
        CommentUpdate: {
            body: string;
        };
        EventUpdate: {
            title?: string;
            description?: string;
            /** Format: date-time */
            start_at?: string;
            /** Format: date-time */
            end_at?: string;
            /** @enum {string} */
            type?: "UNIVERSITY_PARTY" | "BIRTHDAY" | "CLUB" | "CASUAL_HANGOUT" | "BARBECUE" | "AFTER_PARTY" | "GRADUATION" | "SHOW" | "FESTIVAL" | "DINNER" | "TRIP" | "CABULOUS" | "CINEMA";
            audiences?: ("ILUMINADOS" | "VOYEURS" | "ELETRONICOS" | "OTHERS")[];
            location?: {
                /** @default  */
                name: string;
                address: string;
                /** Format: decimal */
                latitude: string;
                /** Format: decimal */
                longitude: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listMes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
        };
    };
    listCommentReads: {
        parameters: {
            query?: {
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 123 */
                        count: number;
                        /**
                         * Format: uri
                         * @example http://api.example.org/accounts/?page=4
                         */
                        next?: string | null;
                        /**
                         * Format: uri
                         * @example http://api.example.org/accounts/?page=2
                         */
                        previous?: string | null;
                        results: components["schemas"]["CommentRead"][];
                    };
                };
            };
        };
    };
    createCommentCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CommentCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["CommentCreate"];
                "multipart/form-data": components["schemas"]["CommentCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentCreate"];
                };
            };
        };
    };
    retrieveCommentRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentRead"];
                };
            };
        };
    };
    updateCommentUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CommentUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["CommentUpdate"];
                "multipart/form-data": components["schemas"]["CommentUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentUpdate"];
                };
            };
        };
    };
    destroyCommentRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    partialUpdateCommentUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CommentUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["CommentUpdate"];
                "multipart/form-data": components["schemas"]["CommentUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentUpdate"];
                };
            };
        };
    };
    listEventReads: {
        parameters: {
            query?: {
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
                starts_from?: string;
                starts_until?: string;
                status?: string;
                type?: string;
                audience?: string;
                participant?: string;
                creator?: string;
                /** @description Um termo de busca. */
                search?: string;
                /** @description Qual campo usar ao ordenar os resultados. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 123 */
                        count: number;
                        /**
                         * Format: uri
                         * @example http://api.example.org/accounts/?page=4
                         */
                        next?: string | null;
                        /**
                         * Format: uri
                         * @example http://api.example.org/accounts/?page=2
                         */
                        previous?: string | null;
                        results: components["schemas"]["EventRead"][];
                    };
                };
            };
        };
    };
    createEventCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["EventCreate"];
                "multipart/form-data": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventCreate"];
                };
            };
        };
    };
    optionsEventRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"];
                };
            };
        };
    };
    retrieveEventRead: {
        parameters: {
            query?: {
                starts_from?: string;
                starts_until?: string;
                status?: string;
                type?: string;
                audience?: string;
                participant?: string;
                creator?: string;
                /** @description Um termo de busca. */
                search?: string;
                /** @description Qual campo usar ao ordenar os resultados. */
                ordering?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"];
                };
            };
        };
    };
    updateEventUpdate: {
        parameters: {
            query?: {
                starts_from?: string;
                starts_until?: string;
                status?: string;
                type?: string;
                audience?: string;
                participant?: string;
                creator?: string;
                /** @description Um termo de busca. */
                search?: string;
                /** @description Qual campo usar ao ordenar os resultados. */
                ordering?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EventUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["EventUpdate"];
                "multipart/form-data": components["schemas"]["EventUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventUpdate"];
                };
            };
        };
    };
    destroyEventRead: {
        parameters: {
            query?: {
                starts_from?: string;
                starts_until?: string;
                status?: string;
                type?: string;
                audience?: string;
                participant?: string;
                creator?: string;
                /** @description Um termo de busca. */
                search?: string;
                /** @description Qual campo usar ao ordenar os resultados. */
                ordering?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    partialUpdateEventUpdate: {
        parameters: {
            query?: {
                starts_from?: string;
                starts_until?: string;
                status?: string;
                type?: string;
                audience?: string;
                participant?: string;
                creator?: string;
                /** @description Um termo de busca. */
                search?: string;
                /** @description Qual campo usar ao ordenar os resultados. */
                ordering?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EventUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["EventUpdate"];
                "multipart/form-data": components["schemas"]["EventUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventUpdate"];
                };
            };
        };
    };
    highlightDetailEventRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                highlight_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"];
                };
            };
        };
    };
    highlightDetailEventRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                highlight_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    highlightDetailEventRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                highlight_pk: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EventRead"];
                "application/x-www-form-urlencoded": components["schemas"]["EventRead"];
                "multipart/form-data": components["schemas"]["EventRead"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"];
                };
            };
        };
    };
    highlightsEventRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"];
                };
            };
        };
    };
    highlightsEventRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EventRead"];
                "application/x-www-form-urlencoded": components["schemas"]["EventRead"];
                "multipart/form-data": components["schemas"]["EventRead"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"];
                };
            };
        };
    };
    participantsEventRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"];
                };
            };
        };
    };
    participantsEventRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EventRead"];
                "application/x-www-form-urlencoded": components["schemas"]["EventRead"];
                "multipart/form-data": components["schemas"]["EventRead"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"];
                };
            };
        };
    };
    photosEventRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"];
                };
            };
        };
    };
    photosEventRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EventRead"];
                "application/x-www-form-urlencoded": components["schemas"]["EventRead"];
                "multipart/form-data": components["schemas"]["EventRead"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"];
                };
            };
        };
    };
    listPhotos: {
        parameters: {
            query?: {
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
                taken_from?: string;
                taken_until?: string;
                uploader?: string;
                event?: string;
                /** @description Um termo de busca. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 123 */
                        count: number;
                        /**
                         * Format: uri
                         * @example http://api.example.org/accounts/?page=4
                         */
                        next?: string | null;
                        /**
                         * Format: uri
                         * @example http://api.example.org/accounts/?page=2
                         */
                        previous?: string | null;
                        results: components["schemas"]["Photo"][];
                    };
                };
            };
        };
    };
    retrievePhoto: {
        parameters: {
            query?: {
                taken_from?: string;
                taken_until?: string;
                uploader?: string;
                event?: string;
                /** @description Um termo de busca. */
                search?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Photo"];
                };
            };
        };
    };
    updatePhoto: {
        parameters: {
            query?: {
                taken_from?: string;
                taken_until?: string;
                uploader?: string;
                event?: string;
                /** @description Um termo de busca. */
                search?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Photo"];
                "application/x-www-form-urlencoded": components["schemas"]["Photo"];
                "multipart/form-data": components["schemas"]["Photo"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Photo"];
                };
            };
        };
    };
    destroyPhoto: {
        parameters: {
            query?: {
                taken_from?: string;
                taken_until?: string;
                uploader?: string;
                event?: string;
                /** @description Um termo de busca. */
                search?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    partialUpdatePhoto: {
        parameters: {
            query?: {
                taken_from?: string;
                taken_until?: string;
                uploader?: string;
                event?: string;
                /** @description Um termo de busca. */
                search?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Photo"];
                "application/x-www-form-urlencoded": components["schemas"]["Photo"];
                "multipart/form-data": components["schemas"]["Photo"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Photo"];
                };
            };
        };
    };
    listhealthchecks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["User"];
                "application/x-www-form-urlencoded": components["schemas"]["User"];
                "multipart/form-data": components["schemas"]["User"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    retrieveUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este Usuário. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este Usuário. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["User"];
                "application/x-www-form-urlencoded": components["schemas"]["User"];
                "multipart/form-data": components["schemas"]["User"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    destroyUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este Usuário. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    partialUpdateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este Usuário. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["User"];
                "application/x-www-form-urlencoded": components["schemas"]["User"];
                "multipart/form-data": components["schemas"]["User"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    createLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": unknown;
                "application/x-www-form-urlencoded": unknown;
                "multipart/form-data": unknown;
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    createRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": unknown;
                "application/x-www-form-urlencoded": unknown;
                "multipart/form-data": unknown;
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    createLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": unknown;
                "application/x-www-form-urlencoded": unknown;
                "multipart/form-data": unknown;
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    createForgotAccess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": unknown;
                "application/x-www-form-urlencoded": unknown;
                "multipart/form-data": unknown;
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    createPasswordResetConfirm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": unknown;
                "application/x-www-form-urlencoded": unknown;
                "multipart/form-data": unknown;
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    createOnboardingFirstAccess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": unknown;
                "application/x-www-form-urlencoded": unknown;
                "multipart/form-data": unknown;
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    cancelEventRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EventRead"];
                "application/x-www-form-urlencoded": components["schemas"]["EventRead"];
                "multipart/form-data": components["schemas"]["EventRead"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"];
                };
            };
        };
    };
    reactivateEventRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EventRead"];
                "application/x-www-form-urlencoded": components["schemas"]["EventRead"];
                "multipart/form-data": components["schemas"]["EventRead"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"];
                };
            };
        };
    };
    restoreEventRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EventRead"];
                "application/x-www-form-urlencoded": components["schemas"]["EventRead"];
                "multipart/form-data": components["schemas"]["EventRead"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"];
                };
            };
        };
    };
    createGithubWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": unknown;
                "application/x-www-form-urlencoded": unknown;
                "multipart/form-data": unknown;
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    createPhotoUploadUrls: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": unknown;
                "application/x-www-form-urlencoded": unknown;
                "multipart/form-data": unknown;
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    createPhotoConfirm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": unknown;
                "application/x-www-form-urlencoded": unknown;
                "multipart/form-data": unknown;
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    createUserUploadSignedUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": unknown;
                "application/x-www-form-urlencoded": unknown;
                "multipart/form-data": unknown;
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    thumbnailEventRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EventRead"];
                "application/x-www-form-urlencoded": components["schemas"]["EventRead"];
                "multipart/form-data": components["schemas"]["EventRead"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"];
                };
            };
        };
    };
    thumbnailEventRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeParticipantEventRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unlinkPhotoActionEventRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                photo_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
