# Generated by Django 6.0.3 on 2026-03-29 22:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscordChannel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("webhook_url", models.URLField(max_length=2048, verbose_name="Webhook URL")),
                (
                    "purpose",
                    models.CharField(
                        choices=[("BOARD_UPDATES", "Board updates")],
                        max_length=64,
                        verbose_name="Purpose",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
            ],
            options={
                "verbose_name": "Discord channel",
                "verbose_name_plural": "Discord channels",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["purpose"], name="comm_discord_purpose_idx"),
                    models.Index(fields=["is_active"], name="comm_discord_active_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("purpose",),
                        name="comm_discord_unique_active_purpose",
                    )
                ],
            },
        ),
    ]
