default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: local
    hooks:
      - id: make-lint
        name: make lint (service)
        entry: make -C service lint
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: make-check
        name: make check (service)
        entry: make -C service check
        language: system
        pass_filenames: false
        stages: [pre-push]
