# Generated by Django 6.0.3 on 2026-07-22 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(
                max_length=5000, validators=[django.core.validators.MaxLengthValidator(5000)]
            ),
        ),
    ]
