# Generated by Django 6.0.3 on 2026-03-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partystatistics",
            name="semester",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1º semestre"), (2, "2º semestre")], verbose_name="Semestre"
            ),
        ),
    ]
