# Generated by Django 6.0.3 on 2026-03-24 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_alter_partystatistics_semester"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="partystatistics",
            index=models.Index(
                fields=["user", "year", "semester"], name="analytics_p_user_id_d272b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partystatistics",
            index=models.Index(
                fields=["user", "party_name"], name="analytics_p_user_id_d2f579_idx"
            ),
        ),
    ]
