# Generated by Django 6.0.3 on 2026-03-26 03:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_users_first_login_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMagicLinkToken",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("token", models.CharField(max_length=128, unique=True, verbose_name="Token")),
                ("expires_at", models.DateTimeField(verbose_name="Expira em")),
                ("used_at", models.DateTimeField(blank=True, null=True, verbose_name="Usado em")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_magic_link_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="magic_link_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de link mágico",
                "verbose_name_plural": "Tokens de link mágico",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["token"], name="users_magic_token_idx"),
                    models.Index(fields=["expires_at"], name="users_magic_expires_idx"),
                    models.Index(fields=["used_at"], name="users_magic_used_idx"),
                ],
            },
        ),
    ]
