# Generated by Django 6.0.3 on 2026-03-31 04:14

import django.db.models.functions.text
import users.models
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0004_usermagiclinktoken"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.ActiveUserManager()),
                ("all_objects", users.models.AllUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Excluído em"),
        ),
        migrations.AlterField(
            model_name="user",
            name="discord_username",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                validators=[users.validators.validate_discord_username_format],
                verbose_name="Usuário do Discord",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                validators=[users.validators.validate_phone_number_format],
                verbose_name="Número de telefone",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[users.validators.validate_username_format],
                verbose_name="Nome de usuário",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("username"), name="users_username_ci_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("deleted_at__isnull", True)),
                name="users_email_ci_unique",
            ),
        ),
    ]
