# Generated by Django 6.0.3 on 2026-04-01 18:35

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_managers_user_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='git_username',
            field=models.CharField(blank=True, default=None, max_length=100, unique=True, verbose_name='Usuário do GitHub'),
        ),
        migrations.AlterField(
            model_name='user',
            name='discord_username',
            field=models.CharField(blank=True, default=None, max_length=100, unique=True, validators=[users.validators.validate_discord_username_format], verbose_name='Usuário do Discord'),
        ),
    ]
