# Generated by Django 6.0.3 on 2026-07-20 19:42

import django.db.models.deletion
import events.managers
import uuid
from typing import Any
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


LEGACY_DEFAULT_AUDIENCE = "OTHERS"


def migrate_legacy_audiences(apps: Any, schema_editor: Any) -> None:
    Event = apps.get_model("events", "Event")
    EventAudience = apps.get_model("events", "EventAudience")
    choices = dict(EventAudience._meta.get_field("audience").choices)
    events = Event.all_objects.all().select_related(None).only("id", "public")
    for event in events:
        audience_value = event.public.upper() if event.public else LEGACY_DEFAULT_AUDIENCE
        if audience_value not in choices:
            audience_value = LEGACY_DEFAULT_AUDIENCE
        EventAudience.objects.update_or_create(
            event_id=event.id,
            audience=audience_value,
            defaults={},
        )


def choose_legacy_creator(apps: Any, schema_editor: Any) -> Any:
    User = apps.get_model("users", "User")
    field_names = {field.name for field in User._meta.get_fields()}
    users = User.objects.all()
    if "deleted_at" in field_names:
        users = users.filter(deleted_at__isnull=True)
    creator = None
    if "is_superuser" in field_names:
        creator = users.filter(is_superuser=True).order_by("id").first()
    creator = creator or users.order_by("id").first()
    if creator is None:
        raise RuntimeError(
            "Nenhum usuário ativo disponível para associar como criador dos eventos existentes. "
            "Crie pelo menos um usuário ativo antes de rodar esta migration."
        )
    return creator


def migrate_event_status(apps: Any, schema_editor: Any) -> None:
    Event = apps.get_model("events", "Event")
    now = timezone.now()
    events = (
        Event.all_objects.all()
        .select_related(None)
        .only("start_at", "end_at", "cancelled_at", "status")
    )
    for event in events:
        start_at = event.start_at
        end_at = event.end_at if event.end_at is not None else start_at
        if event.cancelled_at is not None:
            new_status = "CANCELLED"
        elif now < start_at:
            new_status = "SCHEDULED"
        elif now <= end_at:
            new_status = "IN_PROGRESS"
        else:
            new_status = "COMPLETED"
        if event.status != new_status:
            event.status = new_status
            event.save(update_fields=["status", "updated_at"])


def forwards(apps: Any, schema_editor: Any) -> None:
    migrate_legacy_audiences(apps, schema_editor)
    Event = apps.get_model("events", "Event")
    events_without_creator = Event.all_objects.filter(creator__isnull=True)
    if events_without_creator.exists():
        creator = choose_legacy_creator(apps, schema_editor)
        events_without_creator.update(creator_id=creator.id)
    Event.all_objects.filter(end_at__isnull=True).update(end_at=models.F("start_at"))
    migrate_event_status(apps, schema_editor)


def backwards(apps: Any, schema_editor: Any) -> None:
    Event = apps.get_model("events", "Event")
    EventAudience = apps.get_model("events", "EventAudience")
    fallback_audience = EventAudience._meta.get_field("audience").choices[0][0]
    event_ids = list(Event.all_objects.values_list("id", flat=True))
    audiences_by_event = {}
    audience_rows = (
        EventAudience.objects.filter(event_id__in=event_ids)
        .order_by("created_at", "id")
        .values_list("event_id", "audience")
    )
    for event_id, audience in audience_rows:
        audiences_by_event.setdefault(event_id, audience)
    for event in Event.all_objects.all().only("id"):
        event.public = audiences_by_event.get(event.id, fallback_audience)
        event.save(update_fields=["public"])


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventAudience",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("ILUMINADOS", "Iluminados"),
                            ("VOYEURS", "Voyeurs"),
                            ("ELETRONICOS", "Eletrônicos"),
                            ("OTHERS", "Outros"),
                        ],
                        max_length=30,
                        verbose_name="Público",
                    ),
                ),
            ],
            options={
                "verbose_name": "Público do evento",
                "verbose_name_plural": "Públicos do evento",
                "ordering": ["created_at", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventLocation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                ("street", models.CharField(max_length=255, verbose_name="Logradouro")),
                ("number", models.CharField(max_length=50, verbose_name="Número")),
                (
                    "complement",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Complemento"
                    ),
                ),
                ("neighborhood", models.CharField(max_length=255, verbose_name="Bairro")),
                ("city", models.CharField(max_length=255, verbose_name="Cidade")),
                ("state", models.CharField(max_length=2, verbose_name="UF")),
                ("postal_code", models.CharField(max_length=20, verbose_name="CEP")),
                ("country", models.CharField(default="BR", max_length=2, verbose_name="País")),
                (
                    "latitude",
                    models.DecimalField(decimal_places=6, max_digits=9, verbose_name="Latitude"),
                ),
                (
                    "longitude",
                    models.DecimalField(decimal_places=6, max_digits=10, verbose_name="Longitude"),
                ),
            ],
            options={
                "verbose_name": "Localização",
                "verbose_name_plural": "Localizações",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventParticipant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "verbose_name": "Participante",
                "verbose_name_plural": "Participantes",
                "ordering": ["created_at", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventPhoto",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_thumbnail", models.BooleanField(default=False, verbose_name="Thumbnail")),
            ],
            options={
                "verbose_name": "Foto do evento",
                "verbose_name_plural": "Fotos do evento",
                "ordering": ["created_at", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Highlight",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="Texto")),
            ],
            options={
                "verbose_name": "Highlight",
                "verbose_name_plural": "Highlights",
                "ordering": ["-created_at", "-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HighlightPhoto",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto do highlight",
                "verbose_name_plural": "Fotos do highlight",
                "ordering": ["created_at", "id"],
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["-start_at", "-created_at", "-id"],
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
            },
        ),
        migrations.AlterModelManagers(
            name="event",
            managers=[
                ("objects", events.managers.ActiveEventManager()),
                ("all_objects", events.managers.AllEventManager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name="event",
            name="events_even_public_5bbabb_idx",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="events_type_start_idx",
            old_name="events_even_type_53534a_idx",
        ),
        migrations.AddField(
            model_name="event",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Cancelado em"),
        ),
        migrations.AddField(
            model_name="event",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criador",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Excluído em"),
        ),
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Agendado"),
                    ("IN_PROGRESS", "Em andamento"),
                    ("COMPLETED", "Concluído"),
                    ("CANCELLED", "Cancelado"),
                ],
                max_length=30,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_at",
            field=models.DateTimeField(null=True, verbose_name="Fim do evento"),
        ),
        migrations.AlterField(
            model_name="event",
            name="public",
            field=models.CharField(
                choices=[
                    ("ILUMINADOS", "Iluminados"),
                    ("VOYEURS", "Voyeurs"),
                    ("ELETRONICOS", "Eletrônicos"),
                    ("OTHERS", "Outros"),
                ],
                max_length=30,
                null=True,
                verbose_name="Público",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["status"], name="events_status_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["deleted_at", "start_at"], name="events_deleted_start_idx"),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_at__gte", models.F("start_at"))),
                name="events_end_gte_start",
            ),
        ),
        migrations.AddField(
            model_name="eventaudience",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audiences",
                to="events.event",
                verbose_name="Evento",
            ),
        ),
        migrations.AddField(
            model_name="eventlocation",
            name="event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location",
                to="events.event",
                verbose_name="Evento",
            ),
        ),
        migrations.AddField(
            model_name="eventparticipant",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="added_event_participations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Adicionado por",
            ),
        ),
        migrations.AddField(
            model_name="eventparticipant",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="events.event",
                verbose_name="Evento",
            ),
        ),
        migrations.AddField(
            model_name="eventparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_participations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddField(
            model_name="eventphoto",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_photos",
                to="events.event",
                verbose_name="Evento",
            ),
        ),
        migrations.AddField(
            model_name="eventphoto",
            name="linked_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="linked_event_photos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vinculado por",
            ),
        ),
        migrations.AddField(
            model_name="eventphoto",
            name="photo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_links",
                to="media.photo",
                verbose_name="Foto",
            ),
        ),
        migrations.AddField(
            model_name="highlight",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="authored_highlights",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Autor",
            ),
        ),
        migrations.AddField(
            model_name="highlight",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlights",
                to="events.event",
                verbose_name="Evento",
            ),
        ),
        migrations.AddField(
            model_name="highlightphoto",
            name="highlight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="events.highlight",
                verbose_name="Highlight",
            ),
        ),
        migrations.AddField(
            model_name="highlightphoto",
            name="photo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlight_links",
                to="media.photo",
                verbose_name="Foto",
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="event",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criador",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_at",
            field=models.DateTimeField(verbose_name="Fim do evento"),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Agendado"),
                    ("IN_PROGRESS", "Em andamento"),
                    ("COMPLETED", "Concluído"),
                    ("CANCELLED", "Cancelado"),
                ],
                max_length=30,
                verbose_name="Status",
            ),
        ),
        migrations.RemoveField(
            model_name="event",
            name="public",
        ),
        migrations.RemoveField(
            model_name="event",
            name="thumbnail",
        ),
        migrations.AddConstraint(
            model_name="eventaudience",
            constraint=models.UniqueConstraint(
                fields=("event", "audience"), name="events_audience_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventparticipant",
            constraint=models.UniqueConstraint(
                fields=("event", "user"), name="events_participant_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventphoto",
            constraint=models.UniqueConstraint(
                fields=("event", "photo"), name="events_photo_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventphoto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_thumbnail", True)),
                fields=("event",),
                name="events_one_thumbnail",
            ),
        ),
        migrations.AddConstraint(
            model_name="highlightphoto",
            constraint=models.UniqueConstraint(
                fields=("highlight", "photo"), name="events_highlight_photo_unique"
            ),
        ),
    ]
