# Generated by Django 6.0.3 on 2026-07-20 04:41
from datetime import timezone

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


LEGACY_DEFAULT_AUDIENCE = "OTHERS"


def migrate_legacy_audiences(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    EventAudience = apps.get_model("events", "EventAudience")
    choices = dict(EventAudience._meta.get_field("audience").choices)
    events = Event.objects.all().select_related(None).only("id", "public")
    for event in events:
        audience_value = event.public.upper() if event.public else LEGACY_DEFAULT_AUDIENCE
        if audience_value not in choices:
            audience_value = LEGACY_DEFAULT_AUDIENCE
        EventAudience.objects.update_or_create(
            event_id=event.id,
            audience=audience_value,
            defaults={},
        )


def choose_legacy_creator(apps, schema_editor):
    User = apps.get_model("users", "User")
    creator = (
        User.objects.filter(is_superuser=True, deleted_at__isnull=True)
        .order_by("id")
        .first()
        or User.objects.filter(deleted_at__isnull=True)
        .order_by("id")
        .first()
    )
    if creator is None:
        raise RuntimeError(
            "Nenhum usuário ativo disponível para associar como criador dos eventos existentes. "
            "Crie pelo menos um usuário ativo antes de rodar esta migration."
        )
    return creator


def migrate_event_status(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    now = timezone.now()
    events = Event.objects.all().select_related(None).only(
        "start_at", "end_at", "cancelled_at", "status"
    )
    for event in events:
        start_at = event.start_at
        end_at = event.end_at if event.end_at is not None else start_at
        cancelled_at = event.cancelled_at
        if cancelled_at is not None:
            new_status = "CANCELLED"
        elif now < start_at:
            new_status = "SCHEDULED"
        elif now <= end_at:
            new_status = "IN_PROGRESS"
        else:
            new_status = "COMPLETED"
        if event.status != new_status:
            event.status = new_status
            event.save(update_fields=["status", "updated_at"])


def forwards(apps, schema_editor):
    migrate_legacy_audiences(apps, schema_editor)
    Event = apps.get_model("events", "Event")
    creator = choose_legacy_creator(apps, schema_editor)
    Event.objects.filter(creator__isnull=True).update(creator_id=creator.id)
    Event.objects.filter(end_at__isnull=True).update(end_at=models.F("start_at"))
    migrate_event_status(apps, schema_editor)


def backwards(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    EventAudience = apps.get_model("events", "EventAudience")
    fallback_audience = EventAudience._meta.get_field("audience").choices[0][0]
    event_ids = list(Event.objects.values_list("id", flat=True))
    audiences_by_event = {
        row["event_id"]: row["audience"]
        for row in EventAudience.objects.filter(event_id__in=event_ids)
        .order_by("id")
        .values("event_id", "audience")
    }
    for event in Event.objects.all().only("id"):
        event.public = audiences_by_event.get(event.id, fallback_audience)  # type: ignore[attr-defined]
        event.save(update_fields=["public"])


class Migration(migrations.Migration):
    initial = False

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criador",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Cancelado em",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Excluído em",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Agendado"),
                    ("IN_PROGRESS", "Em andamento"),
                    ("COMPLETED", "Concluído"),
                    ("CANCELLED", "Cancelado"),
                ],
                default="SCHEDULED",
                max_length=30,
                verbose_name="Status",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="EventAudience",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("ILUMINADOS", "Iluminados"),
                            ("VOYEURS", "Voyeurs"),
                            ("ELETRONICOS", "Eletrônicos"),
                            ("OTHERS", "Outros"),
                        ],
                        max_length=30,
                        verbose_name="Público",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audiences",
                        to="events.event",
                        verbose_name="Evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Público do evento",
                "verbose_name_plural": "Públicos do evento",
                "ordering": ["created_at", "id"],
                "abstract": False,
                "constraints": [
                    migrations.UniqueConstraint(
                        fields=["event", "audience"],
                        name="events_audience_unique",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EventParticipant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_event_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Adicionado por",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="events.event",
                        verbose_name="Evento",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participante",
                "verbose_name_plural": "Participantes",
                "ordering": ["created_at", "id"],
                "abstract": False,
                "constraints": [
                    migrations.UniqueConstraint(
                        fields=["event", "user"],
                        name="events_participant_unique",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EventPhoto",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_thumbnail", models.BooleanField(default=False, verbose_name="Thumbnail")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_photos",
                        to="events.event",
                        verbose_name="Evento",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="linked_event_photos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vinculado por",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_links",
                        to="media.photo",
                        verbose_name="Foto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto do evento",
                "verbose_name_plural": "Fotos do evento",
                "ordering": ["created_at", "id"],
                "abstract": False,
                "constraints": [
                    migrations.UniqueConstraint(
                        fields=["event", "photo"],
                        name="events_photo_unique",
                    ),
                    migrations.UniqueConstraint(
                        fields=["event"],
                        condition=models.Q(is_thumbnail=True),
                        name="events_one_thumbnail",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EventLocation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "city",
                    models.CharField(max_length=255, verbose_name="Cidade"),
                ),
                (
                    "complement",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Complemento"),
                ),
                (
                    "country",
                    models.CharField(default="BR", max_length=2, verbose_name="País"),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location",
                        to="events.event",
                        verbose_name="Evento",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(decimal_places=6, max_digits=9, verbose_name="Latitude"),
                ),
                (
                    "longitude",
                    models.DecimalField(decimal_places=6, max_digits=10, verbose_name="Longitude"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                ("neighborhood", models.CharField(max_length=255, verbose_name="Bairro")),
                ("number", models.CharField(max_length=50, verbose_name="Número")),
                ("postal_code", models.CharField(max_length=20, verbose_name="CEP")),
                ("state", models.CharField(max_length=2, verbose_name="UF")),
                ("street", models.CharField(max_length=255, verbose_name="Logradouro")),
            ],
            options={
                "verbose_name": "Localização",
                "verbose_name_plural": "Localizações",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Highlight",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="Texto")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_highlights",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="events.event",
                        verbose_name="Evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Highlight",
                "verbose_name_plural": "Highlights",
                "ordering": ["-created_at", "-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HighlightPhoto",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "highlight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="events.highlight",
                        verbose_name="Highlight",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlight_links",
                        to="media.photo",
                        verbose_name="Foto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto do highlight",
                "verbose_name_plural": "Fotos do highlight",
                "ordering": ["created_at", "id"],
                "abstract": False,
                "constraints": [
                    migrations.UniqueConstraint(
                        fields=["highlight", "photo"],
                        name="events_highlight_photo_unique",
                    ),
                ],
            },
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="event",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criador",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_at",
            field=models.DateTimeField(verbose_name="Fim do evento"),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Agendado"),
                    ("IN_PROGRESS", "Em andamento"),
                    ("COMPLETED", "Concluído"),
                    ("CANCELLED", "Cancelado"),
                ],
                max_length=30,
                verbose_name="Status",
            ),
        ),
        migrations.RemoveField(
            model_name="event",
            name="public",
        ),
        migrations.RemoveField(
            model_name="event",
            name="thumbnail",
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["status"], name="events_status_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["deleted_at", "start_at"], name="events_deleted_start_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(end_at__gte=models.F("start_at")),
                name="events_end_gte_start",
            ),
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["-start_at", "-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["type", "start_at"], name="events_type_start_idx"),
                    models.Index(fields=["status"], name="events_status_idx"),
                    models.Index(
                        fields=["deleted_at", "start_at"], name="events_deleted_start_idx"
                    ),
                ],
                "constraints": [
                    migrations.CheckConstraint(
                        condition=models.Q(end_at__gte=models.F("start_at")),
                        name="events_end_gte_start",
                    ),
                ],
            },
        ),
    ]
