# Generated by Django 6.0.3 on 2026-07-22 04:37

import events.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_domain'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('objects', events.models.EventManager()),
                ('all_objects', events.models.AllEventManager()),
            ],
        ),
    ]
