# Generated by Django 6.0.3 on 2026-07-22 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_add_linked_by_to_eventphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlightphoto',
            options={'ordering': ['created_at'], 'verbose_name': 'Foto do destaque', 'verbose_name_plural': 'Fotos do destaque'},
        ),
        migrations.AddField(
            model_name='highlight',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_highlights', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
