# Generated by Django 6.0.3 on 2026-07-29 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_highlightphoto_options_highlight_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventaudience',
            options={'verbose_name': 'Público do evento', 'verbose_name_plural': 'Públicos do evento'},
        ),
        migrations.AddField(
            model_name='event',
            name='hosts',
            field=models.ManyToManyField(blank=True, related_name='hosted_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Agendado'), ('IN_PROGRESS', 'Em andamento'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='eventaudience',
            name='audience',
            field=models.CharField(choices=[('ILUMINADOS', 'Iluminados'), ('VOYEURS', 'Voyeurs'), ('ELETRONICOS', 'Eletrônicos'), ('OTHERS', 'Outros')], max_length=30, verbose_name='Público-alvo'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='address',
            field=models.TextField(verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='is_thumbnail',
            field=models.BooleanField(default=False, verbose_name='É thumbnail'),
        ),
    ]
