# Generated by Django 6.0.3 on 2026-08-06 00:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_add_hosts"),
        ("events", "0006_alter_eventaudience_options_alter_event_deleted_at_and_more"),
    ]

    operations = []
